# You can print a string directly 
print("Im bad in the walls asbestos");

# You can also print variable values
var hw = "Hello World"; 
print("String: " + hw);

var int_var = 41; 
print("Int: " + int_var);

var float_var = 3.14;
print("Float: " + float_var);

var bool_var = True;
print("Boolean: " + bool_var);

var null_var = NULL;
print("Null Var: " + null_var);

# You can also print multiple things separated by a comma.
print("first", "second");
